language: go

env:
  global: 
    - GO111MODULE=on

before_script:
  - curl -sL https://taskfile.dev/install.sh | sh
  - go get -u github.com/Evertras/go-wasm-rpc/cmd/wasm-rpc-gen

script: ./bin/task build test

go:
- "1.12"

node_js:
- "8.12"
