version: '2'

tasks:
  pack:
    deps:
      - task: pack-spritesheet
        vars:
          NAME: ui
          PATH: ui
      - task: pack-spritesheet
        vars:
          NAME: terrain
          PATH: terrain
      - task: pack-spritesheet
        vars:
          NAME: units
          PATH: units

  pack-spritesheet:
    sources:
      - front/assets/raw/{{.PATH}}/*
    generates:
      - front/assets/{{.NAME}}.png
      - front/assets/{{.NAME}}.json
    cmds:
      - silent: true
        cmd: |
          echo Building {{.NAME}}
          TexturePacker \
            --format pixijs4 \
            --algorithm Basic \
            --extrude 0 \
            --trim-mode None \
            --png-opt-level 0 \
            --disable-auto-alias \
            --shape-padding 2 \
            --sheet front/assets/{{.NAME}}.png \
            --data front/assets/{{.NAME}}.json \
            front/assets/raw/{{.PATH}}
